@startuml cas-etudiant
caption Diagramme de cas d'utilisation — Étudiant

skinparam backgroundColor #FFFFFF
skinparam shadowing false
skinparam defaultFontName "Helvetica"
skinparam nodesep 20
skinparam ranksep 60
skinparam usecase {
  BackgroundColor #EEFDF3
  BorderColor #0F904C
}
skinparam actor {
  BackgroundColor #EEFDF3
  BorderColor #0F904C
}

left to right direction

actor "Étudiant" as Etudiant

rectangle "Plateforme DGBE" {
  usecase "Déposer une demande\nde bourse" as UC2
  usecase "Joindre des pièces\njustificatives" as UC3
  usecase "Soumettre la demande" as UC4
  usecase "Suivre sa demande" as UC5
  usecase "Consulter son historique" as UC6
  usecase "Télécharger ses\nattestations" as UC7
  usecase "Faire une réclamation" as UC8
  usecase "Consulter ses\nnotifications" as UC9
  usecase "S'authentifier" as UC0
  usecase "Créer un compte" as UC1
}

Etudiant --> UC1
Etudiant --> UC2
Etudiant --> UC5
Etudiant --> UC6
Etudiant --> UC7
Etudiant --> UC8
Etudiant --> UC9

UC2 ..> UC0 : <<include>>
UC3 ..> UC2 : <<include>>
UC4 ..> UC2 : <<include>>
UC5 ..> UC0 : <<include>>
UC8 ..> UC0 : <<include>>
UC7 ..> UC5 : <<extend>>

@enduml
